#!/usr/bin/env bash
# Point the local tofu CLI at the Harness-held state for this module.
#
# versions.tf deliberately has no backend block: the Harness IaCM workspace
# supplies one at init time, and anything committed here would override it
# during pipeline runs. So for hand-run plans this script writes the block to
# backend_local.tf, which is git-ignored.
#
# Usage:
#   export TF_HTTP_PASSWORD=<harness PAT>      # needs Workspace Access State
#   ./scripts/backend-local.sh
#   tofu init && tofu plan -var-file=terraform.tfvars
#
# Run it again with --remove to drop the file once you are done.
set -euo pipefail

cd "$(dirname "$0")/.."

ACCOUNT="${HARNESS_ACCOUNT_ID:-8mh-FIIHQUapLuB6K0Cd-w}"
ORG="${HARNESS_ORG_ID:-default}"
PROJECT="${HARNESS_PROJECT_ID:-default_project}"
WORKSPACE="${HARNESS_WORKSPACE_ID:-admin_control_plane}"

if [[ "${1:-}" == "--remove" ]]; then
  rm -f backend_local.tf
  echo ">> removed backend_local.tf — 'tofu init' now has no backend"
  exit 0
fi

if [[ -z "${TF_HTTP_PASSWORD:-}" ]]; then
  echo "TF_HTTP_PASSWORD is unset. Export a Harness PAT with the" >&2
  echo "'Workspace Access State' (iac_workspace_accessstate) permission." >&2
  exit 1
fi

BASE="https://app.harness.io/gateway/iacm/api/orgs/${ORG}/projects/${PROJECT}"
BASE="${BASE}/workspaces/${WORKSPACE}/terraform-backend"

cat > backend_local.tf <<EOF
# Generated by scripts/backend-local.sh — git-ignored, do not commit.
# The username is literally "harness"; the password comes from
# \$TF_HTTP_PASSWORD so no token is written to disk.
terraform {
  backend "http" {
    address        = "${BASE}?accountIdentifier=${ACCOUNT}"
    lock_address   = "${BASE}/lock?accountIdentifier=${ACCOUNT}"
    unlock_address = "${BASE}/lock?accountIdentifier=${ACCOUNT}"
    username       = "harness"
    lock_method    = "POST"
    unlock_method  = "DELETE"
  }
}
EOF

echo ">> wrote backend_local.tf for workspace ${WORKSPACE}"
echo ">> next: tofu init   (add -reconfigure if a previous backend is cached)"
