import "server-only";

import GithubSlugger from "github-slugger";
import type { Element, ElementContent, Root, RootContent } from "hast";
import { toString } from "hast-util-to-string";
import rehypeSanitize from "rehype-sanitize";
import rehypeStringify from "rehype-stringify";
import remarkGfm from "remark-gfm";
import remarkParse from "remark-parse";
import remarkRehype from "remark-rehype";
import { createHighlighter, type Highlighter } from "shiki";
import { unified } from "unified";
import { visit } from "unist-util-visit";

/**
 * Markdown → HTML for lab guides.
 *
 * All of this runs on the server and ships zero markdown code to the browser:
 * a guide is read far more often than it is written, and the reader should not
 * pay to parse a document that was already parsed. The one client-side piece is
 * the copy buttons (`@/components/lab-guide-body`), which attach to markup
 * generated here.
 *
 * Two rules the pipeline order encodes:
 *
 *  1. Raw HTML in the source is dropped, not rendered — `remark-rehype` ignores
 *     it unless `allowDangerousHtml` is set, and it is not set. Authors write
 *     Markdown; they do not get an HTML injection point into a public page.
 *  2. `rehype-sanitize` runs on the author's tree and nothing else. Everything
 *     added afterwards — heading ids, link rels, the entire highlighted code
 *     block — is generated by this file, so sanitising it again would only
 *     strip our own attributes back off.
 */

/** A heading the guide page can build an "on this page" list from. */
export type TocEntry = { id: string; text: string; depth: 2 | 3 };

export type RenderedMarkdown = { html: string; toc: TocEntry[] };

/**
 * Themes for the two colour schemes. Only their *foreground* tokens are used —
 * `globals.css` paints the block with the app's own surface colours, so a code
 * block never arrives with a background that a theme happened to pick.
 */
const THEMES = { light: "github-light-default", dark: "github-dark-default" };

/**
 * Grammars loaded up front. Deliberately a fixed list rather than
 * load-on-demand: a lab guide is rendered inside a request, and a cache miss
 * that has to fetch a grammar mid-render is a stall on the reader's page. This
 * is the set a cloud workshop actually writes — shells, config, IaC, and the
 * handful of languages the exercises are in.
 *
 * An unknown language falls back to unhighlighted text rather than throwing;
 * see `languageFor`.
 */
const LANGS = [
  "bash",
  "shellsession",
  "json",
  "jsonc",
  "yaml",
  "hcl",
  "terraform",
  "typescript",
  "javascript",
  "tsx",
  "python",
  "go",
  "java",
  "groovy",
  "sql",
  "dockerfile",
  "diff",
  "markdown",
  "html",
  "css",
  "xml",
  "toml",
  "ini",
  "powershell",
];

/** How a language is named in the block's header, where it differs. */
const LANG_LABELS: Record<string, string> = {
  bash: "Shell",
  shellsession: "Shell session",
  hcl: "Terraform",
  terraform: "Terraform",
  tsx: "TSX",
  jsonc: "JSON",
  yaml: "YAML",
  json: "JSON",
  sql: "SQL",
  html: "HTML",
  css: "CSS",
  xml: "XML",
  toml: "TOML",
  ini: "INI",
  text: "Text",
};

/**
 * One highlighter per process, created on first use.
 *
 * Creating it loads every grammar above, so it is far too expensive to do per
 * request — and far too expensive to do at module load, which would put it on
 * the cold start of every page in the app rather than only the guides.
 */
let highlighterPromise: Promise<Highlighter> | null = null;

function getHighlighter(): Promise<Highlighter> {
  highlighterPromise ??= createHighlighter({
    themes: Object.values(THEMES),
    langs: LANGS,
  });
  return highlighterPromise;
}

const isElement = (node: RootContent, tagName: string): node is Element =>
  node.type === "element" && node.tagName === tagName;

/* ------------------------------------------------------------------ *
 * Code fence info strings
 * ------------------------------------------------------------------ */

/**
 * Carry a fence's title through sanitisation.
 *
 * ```` ```bash title="setup.sh" ```` puts "setup.sh" in the mdast node's meta,
 * which `rehype-sanitize` drops — it rebuilds every node from the attributes
 * its schema allows, and `data` is not an attribute. The class name *does*
 * survive (the default schema keeps `language-*` on `code`), so the title is
 * folded into it here and unpacked again on the other side.
 *
 * Encoded because a class attribute cannot contain spaces, and "Step 2 — main.tf"
 * is exactly the sort of title somebody will write.
 */
function rehypeCarryCodeTitle() {
  return (tree: Root) => {
    visit(tree, "element", (node: Element) => {
      if (node.tagName !== "code") return;

      const meta = (node.data as { meta?: string } | undefined)?.meta;
      if (!meta) return;

      const title = meta.match(/(?:^|\s)title=(?:"([^"]*)"|'([^']*)'|(\S+))/);
      const value = title?.[1] ?? title?.[2] ?? title?.[3];
      if (!value) return;

      const classes = Array.isArray(node.properties.className)
        ? node.properties.className
        : [];
      const lang = classes.find(
        (c) => typeof c === "string" && c.startsWith("language-"),
      );
      if (typeof lang !== "string") return;

      node.properties.className = classes.map((c) =>
        c === lang ? `${lang}:${encodeURIComponent(value)}` : c,
      );
    });
  };
}

/** The language and optional title a fence asked for. */
function parseInfo(code: Element): { lang: string; title: string | null } {
  const classes = Array.isArray(code.properties.className)
    ? code.properties.className
    : [];
  const marker = classes.find(
    (c): c is string => typeof c === "string" && c.startsWith("language-"),
  );
  if (!marker) return { lang: "text", title: null };

  const [lang, encoded] = marker.slice("language-".length).split(":", 2);
  let title: string | null = null;
  if (encoded) {
    try {
      title = decodeURIComponent(encoded);
    } catch {
      // A title that survived this far but won't decode isn't worth a 500.
      title = encoded;
    }
  }
  return { lang: lang.toLowerCase() || "text", title };
}

/* ------------------------------------------------------------------ *
 * Code blocks
 * ------------------------------------------------------------------ */

const el = (
  tagName: string,
  properties: Element["properties"],
  children: ElementContent[] = [],
): Element => ({ type: "element", tagName, properties, children });

/**
 * The clipboard glyph, inline rather than from `lucide-react` — this markup is
 * built as hast on the server, where a React component is not available. The
 * "copied" tick is a sibling; `globals.css` swaps which one is visible.
 *
 * `data-nocopy` marks everything that is chrome rather than code: the copy
 * handler strips these before reading the text, so the buttons and the line
 * numbers never end up on the clipboard.
 */
function icon(kind: "clipboard" | "check"): Element {
  const paths =
    kind === "clipboard"
      ? [
          "M9 4h6a1 1 0 0 1 1 1v1H8V5a1 1 0 0 1 1-1z",
          "M8 6H6a2 2 0 0 0-2 2v11a2 2 0 0 0 2 2h12a2 2 0 0 0 2-2V8a2 2 0 0 0-2-2h-2",
        ]
      : ["M5 13l4 4L19 7"];

  return el(
    "svg",
    {
      "aria-hidden": "true",
      viewBox: "0 0 24 24",
      fill: "none",
      stroke: "currentColor",
      strokeWidth: "2",
      strokeLinecap: "round",
      strokeLinejoin: "round",
      className: [`code-icon`, `code-icon-${kind}`],
    },
    paths.map((d) => el("path", { d })),
  );
}

/** Copy the whole block. Lives in the block header, always visible. */
function blockCopyButton(): Element {
  return el(
    "button",
    {
      type: "button",
      className: ["code-copy"],
      "data-copy": "block",
      "data-nocopy": "true",
      "aria-label": "Copy code",
    },
    [
      icon("clipboard"),
      icon("check"),
      el("span", { className: ["code-copy-label"] }, [
        { type: "text", value: "Copy" },
      ]),
      el("span", { className: ["code-copy-done"] }, [
        { type: "text", value: "Copied" },
      ]),
    ],
  );
}

/**
 * The per-line control: a line number that turns into a copy button.
 *
 * Doubling the two is deliberate. A gutter of numbers is worth having on its
 * own — half of running a lab is somebody saying "the export on line 4" — and
 * hanging the copy affordance off it means a line costs one control instead of
 * two, with nothing hovering over the code until the pointer is on that line.
 */
function lineCopyButton(lineNumber: number): Element {
  return el(
    "button",
    {
      type: "button",
      className: ["code-line-copy"],
      "data-copy": "line",
      "data-nocopy": "true",
      tabIndex: -1,
      "aria-label": `Copy line ${lineNumber}`,
      title: `Copy line ${lineNumber}`,
    },
    [
      el("span", { className: ["code-line-no"] }, [
        { type: "text", value: String(lineNumber) },
      ]),
      icon("clipboard"),
      icon("check"),
    ],
  );
}

/**
 * Replace every ```<pre><code>``` with a highlighted, copyable block.
 *
 * Runs after sanitisation, so everything it builds is trusted by construction:
 * the only author-supplied value that survives into the output is the code
 * text itself, which Shiki tokenises into text nodes.
 */
function rehypeHighlight(highlighter: Highlighter) {
  const loaded = new Set(highlighter.getLoadedLanguages());

  return (tree: Root) => {
    visit(tree, "element", (node: Element, index, parent) => {
      if (node.tagName !== "pre" || !parent || index === undefined) return;

      const code = node.children.find((c) => isElement(c, "code"));
      if (!code || code.type !== "element") return;

      const { lang, title } = parseInfo(code);
      const language = loaded.has(lang) ? lang : "text";
      // Markdown fences always end in a newline; keeping it would render an
      // empty final line, complete with its own line number.
      const source = toString(code).replace(/\n$/, "");

      const highlighted = highlighter.codeToHast(source, {
        lang: language,
        themes: THEMES,
        // Emit both themes as CSS variables instead of picking one at render
        // time. The server has no idea which scheme the reader is in — the
        // theme is applied by a class on <html> in the browser — so the block
        // has to carry both and let CSS choose.
        defaultColor: false,
      });

      const pre = highlighted.children.find(
        (c): c is Element => c.type === "element" && c.tagName === "pre",
      );
      if (!pre) return;

      const codeEl = pre.children.find(
        (c): c is Element => c.type === "element" && c.tagName === "code",
      );

      // Shiki separates its line spans with literal newlines, which is how a
      // `<pre>` normally breaks them. These lines are laid out as blocks
      // instead — a block is what gives the line gutter something to stick to —
      // so those newlines would each open a second, empty line box and double
      // the leading. Dropping them here means the *rendered* text no longer
      // carries the line breaks, which is why the copy handler rebuilds them
      // from the line elements rather than reading `textContent`.
      if (codeEl) {
        codeEl.children = codeEl.children.filter(
          (c) => !(c.type === "text" && c.value.trim().length === 0),
        );
      }

      // Number every line, but only when there is more than one: a single
      // shell command is not a listing, and a lone "1" beside it is noise the
      // block's own copy button already covers.
      const lines =
        codeEl?.children.filter(
          (c): c is Element =>
            c.type === "element" &&
            typeof c.properties?.class === "string" &&
            c.properties.class.split(" ").includes("line"),
        ) ?? [];

      if (lines.length > 1) {
        lines.forEach((line, i) => {
          // Blank lines get a number for alignment but nothing to copy.
          const blank = toString(line).trim().length === 0;
          line.children.unshift(
            blank
              ? el(
                  "span",
                  {
                    className: ["code-line-copy", "is-blank"],
                    "data-nocopy": "true",
                    "aria-hidden": "true",
                  },
                  [
                    el("span", { className: ["code-line-no"] }, [
                      { type: "text", value: String(i + 1) },
                    ]),
                  ],
                )
              : lineCopyButton(i + 1),
          );
        });
        addClass(pre, "has-line-numbers");
      }

      const label = LANG_LABELS[language] ?? language;

      parent.children[index] = el(
        "figure",
        { className: ["lab-code"], "data-lang": language },
        [
          el("figcaption", { className: ["lab-code-head"] }, [
            el("span", { className: ["lab-code-title"] }, [
              { type: "text", value: title ?? label },
            ]),
            // With a filename shown, the language becomes the secondary label.
            ...(title
              ? [
                  el("span", { className: ["lab-code-lang"] }, [
                    { type: "text", value: label },
                  ]),
                ]
              : []),
            blockCopyButton(),
          ]),
          pre,
        ],
      );

      // Children were replaced wholesale; there is nothing inside to visit.
      return "skip";
    });
  };
}

/**
 * Add a class to an element that already has some.
 *
 * Fussier than it looks. Shiki writes its classes under the property key
 * `class`, while hast's own convention is `className` — and the serialiser maps
 * *both* to a `class` attribute. Setting the one Shiki did not use produces an
 * element with two `class` attributes, of which the browser honours the first
 * and silently drops the second. So whichever key is already there is the one
 * that gets extended.
 */
function addClass(node: Element, name: string): void {
  const key = "className" in node.properties ? "className" : "class";
  const current = node.properties[key];

  const existing: string[] = (
    Array.isArray(current)
      ? current.map(String)
      : typeof current === "string"
        ? current.split(" ")
        : []
  ).filter(Boolean);

  if (existing.includes(name)) return;

  // hast types `className` as a list and any other key as a scalar; both
  // serialise to the same attribute.
  if (key === "className") node.properties.className = [...existing, name];
  else node.properties.class = [...existing, name].join(" ");
}

/* ------------------------------------------------------------------ *
 * Headings and links
 * ------------------------------------------------------------------ */

/**
 * Give every h2/h3 a stable id and collect them for the page's contents list.
 *
 * The slugger is created per document rather than per plugin instance: it
 * remembers what it has already issued so a guide with two "Verify" sections
 * gets `verify` and `verify-1`, and a shared one would carry that state across
 * unrelated guides.
 */
function rehypeHeadings() {
  return (tree: Root, file: { data: Record<string, unknown> }) => {
    const slugger = new GithubSlugger();
    const toc: TocEntry[] = [];

    visit(tree, "element", (node: Element) => {
      if (node.tagName !== "h2" && node.tagName !== "h3") return;

      const text = toString(node);
      const id =
        typeof node.properties.id === "string" && node.properties.id.length > 0
          ? node.properties.id
          : slugger.slug(text || "section");

      node.properties.id = id;
      // The whole heading is the anchor, so the target is as big as the words
      // rather than a link icon that has to be hunted for on hover.
      node.children = [
        el("a", { href: `#${id}`, className: ["heading-anchor"] }, node.children),
      ];

      toc.push({ id, text, depth: node.tagName === "h2" ? 2 : 3 });
    });

    file.data.toc = toc;
  };
}

/**
 * Send off-site links to a new tab. `noopener` is the point — `noreferrer` for
 * the same reason it always is — since a guide is a public page and the link
 * target is whatever a manager typed.
 */
function rehypeExternalLinks() {
  return (tree: Root) => {
    visit(tree, "element", (node: Element) => {
      if (node.tagName !== "a") return;
      const href = node.properties.href;
      if (typeof href !== "string" || !/^https?:\/\//i.test(href)) return;

      node.properties.target = "_blank";
      node.properties.rel = ["noopener", "noreferrer"];
    });
  };
}

/* ------------------------------------------------------------------ *
 * The pipeline
 * ------------------------------------------------------------------ */

const buildProcessor = (highlighter: Highlighter) =>
  unified()
    .use(remarkParse)
    .use(remarkGfm)
    .use(remarkRehype)
    .use(rehypeCarryCodeTitle)
    // GitHub's default rules, which already keep `language-*` on a code
    // element — `language-hcl:main.tf` included, which is what lets the fence
    // title survive this step.
    .use(rehypeSanitize)
    // Everything below this line generates trusted markup.
    .use(rehypeHighlight, highlighter)
    .use(rehypeHeadings)
    .use(rehypeExternalLinks)
    .use(rehypeStringify);

/**
 * The pipeline, built once. Plugins hold no per-document state — the one that
 * would, the heading slugger, creates its own inside the transform — so a
 * single processor is safe to share across concurrent requests.
 */
let processorPromise: Promise<ReturnType<typeof buildProcessor>> | null = null;

function getProcessor() {
  processorPromise ??= getHighlighter().then(buildProcessor);
  return processorPromise;
}

/** Render a guide body to HTML, with the headings it turned out to have. */
export async function renderMarkdown(
  markdown: string,
): Promise<RenderedMarkdown> {
  if (markdown.trim().length === 0) return { html: "", toc: [] };

  const processor = await getProcessor();
  const file = await processor.process(markdown);

  return {
    html: String(file),
    toc: (file.data as { toc?: TocEntry[] }).toc ?? [],
  };
}
