import "server-only";

import GithubSlugger from "github-slugger";
import type { Element, ElementContent, Root, RootContent } from "hast";
import { toString } from "hast-util-to-string";
import type { Paragraph, Root as MdastRoot } from "mdast";
import rehypeSanitize from "rehype-sanitize";
import rehypeStringify from "rehype-stringify";
import remarkDirective from "remark-directive";
import remarkGfm from "remark-gfm";
import remarkParse from "remark-parse";
import remarkRehype from "remark-rehype";
import { createHighlighter, type Highlighter } from "shiki";
import { unified } from "unified";
import { SKIP, visit } from "unist-util-visit";

/**
 * Markdown → HTML for lab guides.
 *
 * All of this runs on the server and ships zero markdown code to the browser:
 * a guide is read far more often than it is written, and the reader should not
 * pay to parse a document that was already parsed. The one client-side piece is
 * the copy buttons (`@/components/lab-guide-body`), which attach to markup
 * generated here.
 *
 * Two rules the pipeline order encodes:
 *
 *  1. Raw HTML in the source is dropped, not rendered — `remark-rehype` ignores
 *     it unless `allowDangerousHtml` is set, and it is not set. Authors write
 *     Markdown; they do not get an HTML injection point into a public page.
 *  2. `rehype-sanitize` runs on the author's tree and nothing else. Everything
 *     added afterwards — heading ids, link rels, the entire highlighted code
 *     block — is generated by this file, so sanitising it again would only
 *     strip our own attributes back off.
 */

/** A heading the guide page can build an "on this page" list from. */
export type TocEntry = { id: string; text: string; depth: 2 | 3 };

export type RenderedMarkdown = { html: string; toc: TocEntry[] };

/**
 * Themes for the two colour schemes. Only their *foreground* tokens are used —
 * `globals.css` paints the block with the app's own surface colours, so a code
 * block never arrives with a background that a theme happened to pick.
 */
const THEMES = { light: "github-light-default", dark: "github-dark-default" };

/**
 * Grammars loaded up front. Deliberately a fixed list rather than
 * load-on-demand: a lab guide is rendered inside a request, and a cache miss
 * that has to fetch a grammar mid-render is a stall on the reader's page. This
 * is the set a cloud workshop actually writes — shells, config, IaC, and the
 * handful of languages the exercises are in.
 *
 * An unknown language falls back to unhighlighted text rather than throwing;
 * see `languageFor`.
 */
const LANGS = [
  "bash",
  "shellsession",
  "json",
  "jsonc",
  "yaml",
  "hcl",
  "terraform",
  "typescript",
  "javascript",
  "tsx",
  "python",
  "go",
  "java",
  "groovy",
  "sql",
  "dockerfile",
  "diff",
  "markdown",
  "html",
  "css",
  "xml",
  "toml",
  "ini",
  "powershell",
];

/** How a language is named in the block's header, where it differs. */
const LANG_LABELS: Record<string, string> = {
  bash: "Shell",
  shellsession: "Shell session",
  hcl: "Terraform",
  terraform: "Terraform",
  tsx: "TSX",
  jsonc: "JSON",
  yaml: "YAML",
  json: "JSON",
  sql: "SQL",
  html: "HTML",
  css: "CSS",
  xml: "XML",
  toml: "TOML",
  ini: "INI",
  text: "Text",
};

/**
 * One highlighter per process, created on first use.
 *
 * Creating it loads every grammar above, so it is far too expensive to do per
 * request — and far too expensive to do at module load, which would put it on
 * the cold start of every page in the app rather than only the guides.
 */
let highlighterPromise: Promise<Highlighter> | null = null;

function getHighlighter(): Promise<Highlighter> {
  highlighterPromise ??= createHighlighter({
    themes: Object.values(THEMES),
    langs: LANGS,
  });
  return highlighterPromise;
}

const isElement = (node: RootContent, tagName: string): node is Element =>
  node.type === "element" && node.tagName === tagName;

/* ------------------------------------------------------------------ *
 * Code fence info strings
 * ------------------------------------------------------------------ */

/**
 * Carry a fence's title through sanitisation.
 *
 * ```` ```bash title="setup.sh" ```` puts "setup.sh" in the mdast node's meta,
 * which `rehype-sanitize` drops — it rebuilds every node from the attributes
 * its schema allows, and `data` is not an attribute. The class name *does*
 * survive (the default schema keeps `language-*` on `code`), so the title is
 * folded into it here and unpacked again on the other side.
 *
 * Encoded because a class attribute cannot contain spaces, and "Step 2 — main.tf"
 * is exactly the sort of title somebody will write.
 */
function rehypeCarryCodeTitle() {
  return (tree: Root) => {
    visit(tree, "element", (node: Element) => {
      if (node.tagName !== "code") return;

      const meta = (node.data as { meta?: string } | undefined)?.meta;
      if (!meta) return;

      const title = meta.match(/(?:^|\s)title=(?:"([^"]*)"|'([^']*)'|(\S+))/);
      const value = title?.[1] ?? title?.[2] ?? title?.[3];
      if (!value) return;

      const classes = Array.isArray(node.properties.className)
        ? node.properties.className
        : [];
      const lang = classes.find(
        (c) => typeof c === "string" && c.startsWith("language-"),
      );
      if (typeof lang !== "string") return;

      node.properties.className = classes.map((c) =>
        c === lang ? `${lang}:${encodeURIComponent(value)}` : c,
      );
    });
  };
}

/** The language and optional title a fence asked for. */
function parseInfo(code: Element): { lang: string; title: string | null } {
  const classes = Array.isArray(code.properties.className)
    ? code.properties.className
    : [];
  const marker = classes.find(
    (c): c is string => typeof c === "string" && c.startsWith("language-"),
  );
  if (!marker) return { lang: "text", title: null };

  const [lang, encoded] = marker.slice("language-".length).split(":", 2);
  let title: string | null = null;
  if (encoded) {
    try {
      title = decodeURIComponent(encoded);
    } catch {
      // A title that survived this far but won't decode isn't worth a 500.
      title = encoded;
    }
  }
  return { lang: lang.toLowerCase() || "text", title };
}

/* ------------------------------------------------------------------ *
 * List indentation
 * ------------------------------------------------------------------ */

/** A line that opens a list item: its indent, its marker, the gap after it. */
const LIST_ITEM = /^([ \t]*)([-*+]|\d{1,9}[.)])([ \t]+)(?=\S)/;

/** A fence, once the line's indent (and any list marker) is off the front. */
const FENCE = /^(`{3,}|~{3,})(.*)$/;

/** How far past a marker's own indent a line has to be to be inside the item. */
const CONTINUATION = 2;

/** Leading whitespace as a column, counting a tab to the next stop of four. */
function indentWidth(line: string): number {
  let width = 0;
  for (const ch of line) {
    if (ch === " ") width += 1;
    else if (ch === "\t") width += 4 - (width % 4);
    else break;
  }
  return width;
}

/** Move a line right, leaving blank lines blank. */
const shiftLine = (line: string, by: number): string =>
  by > 0 && line.trim().length > 0 ? " ".repeat(by) + line : line;

/**
 * Re-indent under-indented blocks so they stay in the list item they follow.
 *
 * Markdown keeps a block inside a list item only while it is indented to that
 * item's *content column* — three for `1. `, four for `10. `, two for `- `. A
 * fence or an image one space short of that closes the list instead, and the
 * steps below it become a second list numbered from one. Nothing about the
 * source shows it: two spaces looks indented, and the rule that two is enough
 * under a bullet but not under a number is not one anybody should have to hold
 * in their head while writing a lab.
 *
 * So the guides get one rule — two spaces means "still inside this step" — and
 * this pass turns that into whatever column the parser actually wants, before
 * the parser sees it. Indenting is all it does: a line is only ever moved
 * right, and only ever to the content column of the item it is already inside,
 * so a correctly indented guide passes through untouched.
 *
 * Line-for-line, deliberately. The editor's preview lines its scroll up against
 * `data-line`, and every one of those numbers comes from parsing what this
 * function returns — so it may change what a line starts with, but never how
 * many there are.
 *
 * Fenced code is copied through with the shift its opening fence got and
 * nothing else: a list marker is only a list marker in prose, and these guides
 * are full of YAML, whose every sequence entry would otherwise open an item and
 * drag the rest of the block in after it.
 */
function normaliseListIndents(markdown: string): string {
  const lines = markdown.split("\n");
  const out: string[] = [];

  /** The list items currently open, outermost first. */
  const open: { srcIndent: number; contentColumn: number }[] = [];
  /** The fence being copied through, if the walk is inside one. */
  let fence: { marker: string; by: number; floor: number } | null = null;

  for (const line of lines) {
    if (fence) {
      // Code keeps its shape relative to its fence, but no line may sit left
      // of the item's content column: a fence moved into a step takes its
      // contents with it, and a line short of that column would end the step —
      // closing the block early and spilling the rest of the code into the
      // page as prose.
      out.push(
        shiftLine(line, Math.max(fence.by, fence.floor - indentWidth(line))),
      );

      // A closing fence is the same character, at least as long, and alone on
      // its line — anything else is code that happens to start with backticks.
      const close = line.trim().match(FENCE);
      if (
        close &&
        close[1][0] === fence.marker[0] &&
        close[1].length >= fence.marker.length &&
        close[2].trim().length === 0
      ) {
        fence = null;
      }
      continue;
    }

    // A blank line separates blocks but does not end a list, so it neither
    // closes an item nor needs moving.
    if (line.trim().length === 0) {
      out.push(line);
      continue;
    }

    const width = indentWidth(line);

    // Anything not far enough in has left the items it is not far enough for.
    while (
      open.length > 0 &&
      width < open[open.length - 1].srcIndent + CONTINUATION
    ) {
      open.pop();
    }

    const item = open[open.length - 1];
    const by = item ? Math.max(0, item.contentColumn - width) : 0;
    out.push(shiftLine(line, by));

    const opened = line.match(LIST_ITEM);
    if (opened) {
      // Where this item's own content starts, in the output.
      const marker = opened[2].length + opened[3].length;
      open.push({ srcIndent: width, contentColumn: width + by + marker });
    }

    // A fence opens on its own line, or directly after a marker on the line
    // that opened the item.
    const rest = opened ? line.slice(opened[0].length) : line.trimStart();
    const start = rest.match(FENCE);
    if (start) {
      // A fence on a marker line belongs to the item that marker just opened.
      const inner = opened ? open[open.length - 1] : item;
      fence = { marker: start[1], by, floor: inner?.contentColumn ?? 0 };
    }
  }

  return out.join("\n");
}

/* ------------------------------------------------------------------ *
 * Collapsible sections
 * ------------------------------------------------------------------ */

/** The heading on a collapsible section that was opened without one. */
const DEFAULT_SUMMARY = "Details";

/**
 * `:::details[Show the answer]` … `:::` → a `<details>` block.
 *
 * A directive rather than raw HTML, because raw HTML never reaches the output:
 * `remark-rehype` runs without `allowDangerousHtml`, and that stays true — a
 * guide body is not an HTML injection point. `remark-directive` adds one
 * generic block syntax instead, and this plugin decides what it may mean.
 *
 * The `details` and `summary` elements are built *here*, before sanitisation,
 * rather than afterwards like the code blocks: both tags are already in the
 * default schema, so they survive it, and building them in mdast means the
 * heading and the body are ordinary Markdown that gets sanitised along with
 * everything else. Only the decoration — classes, the chevron, the body
 * wrapper — is added on the trusted side, in `rehypeDetails`.
 *
 * `:::details[Title]{open}` starts expanded.
 *
 * Everything else the syntax can match is put back as the text that was typed.
 * That is the whole reason this runs as one pass over every directive node:
 * turning the extension on also makes `:name` a directive *mid-sentence*, so a
 * guide that says `key:value` — and these guides are full of that — would
 * otherwise lose the second half of the word. Directives are a feature of this
 * one block form; anywhere else the punctuation means what it looks like.
 */
function remarkDetails() {
  return (tree: MdastRoot, file: { value: unknown }) => {
    const source = String(file.value);

    visit(tree, (node, index, parent) => {
      if (
        node.type !== "containerDirective" &&
        node.type !== "leafDirective" &&
        node.type !== "textDirective"
      ) {
        return;
      }

      if (node.type !== "containerDirective" || node.name !== "details") {
        const start = node.position?.start.offset;
        const end = node.position?.end.offset;
        if (!parent || index === undefined || start === undefined || end === undefined) {
          return SKIP;
        }

        parent.children[index] = {
          type: "text",
          value: source.slice(start, end),
          position: node.position,
        };
        // The node is detached; its children are not part of the document.
        return SKIP;
      }

      // `:::details[Title]` puts the label in a leading paragraph, flagged as
      // such. Without one there is nothing to click, so the section gets a
      // generic heading rather than a summary that is a blank strip.
      const [first] = node.children;
      const labelled =
        first?.type === "paragraph" &&
        (first.data as { directiveLabel?: boolean } | undefined)
          ?.directiveLabel === true;

      const summary: Paragraph = labelled
        ? first
        : {
            type: "paragraph",
            children: [{ type: "text", value: DEFAULT_SUMMARY }],
          };

      summary.data = { ...summary.data, hName: "summary" };
      node.children = [
        summary,
        ...(labelled ? node.children.slice(1) : node.children),
      ];

      node.data = {
        ...node.data,
        hName: "details",
        hProperties: { open: node.attributes?.open !== undefined },
      };
    });
  };
}

/* ------------------------------------------------------------------ *
 * Code blocks
 * ------------------------------------------------------------------ */

const el = (
  tagName: string,
  properties: Element["properties"],
  children: ElementContent[] = [],
): Element => ({ type: "element", tagName, properties, children });

/**
 * The clipboard glyph, inline rather than from `lucide-react` — this markup is
 * built as hast on the server, where a React component is not available. The
 * "copied" tick is a sibling; `globals.css` swaps which one is visible.
 *
 * `data-nocopy` marks everything that is chrome rather than code: the copy
 * handler strips these before reading the text, so the buttons and the line
 * numbers never end up on the clipboard.
 */
function icon(kind: "clipboard" | "check"): Element {
  const paths =
    kind === "clipboard"
      ? [
          "M9 4h6a1 1 0 0 1 1 1v1H8V5a1 1 0 0 1 1-1z",
          "M8 6H6a2 2 0 0 0-2 2v11a2 2 0 0 0 2 2h12a2 2 0 0 0 2-2V8a2 2 0 0 0-2-2h-2",
        ]
      : ["M5 13l4 4L19 7"];

  return el(
    "svg",
    {
      "aria-hidden": "true",
      viewBox: "0 0 24 24",
      fill: "none",
      stroke: "currentColor",
      strokeWidth: "2",
      strokeLinecap: "round",
      strokeLinejoin: "round",
      className: [`code-icon`, `code-icon-${kind}`],
    },
    paths.map((d) => el("path", { d })),
  );
}

/** Copy the whole block. Lives in the block header, always visible. */
function blockCopyButton(): Element {
  return el(
    "button",
    {
      type: "button",
      className: ["code-copy"],
      "data-copy": "block",
      "data-nocopy": "true",
      "aria-label": "Copy code",
    },
    [
      icon("clipboard"),
      icon("check"),
      el("span", { className: ["code-copy-label"] }, [
        { type: "text", value: "Copy" },
      ]),
      el("span", { className: ["code-copy-done"] }, [
        { type: "text", value: "Copied" },
      ]),
    ],
  );
}

/**
 * The per-line control: a line number that turns into a copy button.
 *
 * Doubling the two is deliberate. A gutter of numbers is worth having on its
 * own — half of running a lab is somebody saying "the export on line 4" — and
 * hanging the copy affordance off it means a line costs one control instead of
 * two, with nothing hovering over the code until the pointer is on that line.
 */
function lineCopyButton(lineNumber: number): Element {
  return el(
    "button",
    {
      type: "button",
      className: ["code-line-copy"],
      "data-copy": "line",
      "data-nocopy": "true",
      tabIndex: -1,
      "aria-label": `Copy line ${lineNumber}`,
      title: `Copy line ${lineNumber}`,
    },
    [
      el("span", { className: ["code-line-no"] }, [
        { type: "text", value: String(lineNumber) },
      ]),
      icon("clipboard"),
      icon("check"),
    ],
  );
}

/**
 * Replace every ```<pre><code>``` with a highlighted, copyable block.
 *
 * Runs after sanitisation, so everything it builds is trusted by construction:
 * the only author-supplied value that survives into the output is the code
 * text itself, which Shiki tokenises into text nodes.
 */
function rehypeHighlight(highlighter: Highlighter) {
  const loaded = new Set(highlighter.getLoadedLanguages());

  return (tree: Root) => {
    visit(tree, "element", (node: Element, index, parent) => {
      if (node.tagName !== "pre" || !parent || index === undefined) return;

      const code = node.children.find((c) => isElement(c, "code"));
      if (!code || code.type !== "element") return;

      const { lang, title } = parseInfo(code);
      const language = loaded.has(lang) ? lang : "text";
      // Markdown fences always end in a newline; keeping it would render an
      // empty final line, complete with its own line number.
      const source = toString(code).replace(/\n$/, "");

      const highlighted = highlighter.codeToHast(source, {
        lang: language,
        themes: THEMES,
        // Emit both themes as CSS variables instead of picking one at render
        // time. The server has no idea which scheme the reader is in — the
        // theme is applied by a class on <html> in the browser — so the block
        // has to carry both and let CSS choose.
        defaultColor: false,
      });

      const pre = highlighted.children.find(
        (c): c is Element => c.type === "element" && c.tagName === "pre",
      );
      if (!pre) return;

      const codeEl = pre.children.find(
        (c): c is Element => c.type === "element" && c.tagName === "code",
      );

      // Shiki separates its line spans with literal newlines, which is how a
      // `<pre>` normally breaks them. These lines are laid out as blocks
      // instead — a block is what gives the line gutter something to stick to —
      // so those newlines would each open a second, empty line box and double
      // the leading. Dropping them here means the *rendered* text no longer
      // carries the line breaks, which is why the copy handler rebuilds them
      // from the line elements rather than reading `textContent`.
      if (codeEl) {
        codeEl.children = codeEl.children.filter(
          (c) => !(c.type === "text" && c.value.trim().length === 0),
        );
      }

      // Number every line, but only when there is more than one: a single
      // shell command is not a listing, and a lone "1" beside it is noise the
      // block's own copy button already covers.
      const lines =
        codeEl?.children.filter(
          (c): c is Element =>
            c.type === "element" &&
            typeof c.properties?.class === "string" &&
            c.properties.class.split(" ").includes("line"),
        ) ?? [];

      if (lines.length > 1) {
        lines.forEach((line, i) => {
          // Blank lines get a number for alignment but nothing to copy.
          const blank = toString(line).trim().length === 0;
          line.children.unshift(
            blank
              ? el(
                  "span",
                  {
                    className: ["code-line-copy", "is-blank"],
                    "data-nocopy": "true",
                    "aria-hidden": "true",
                  },
                  [
                    el("span", { className: ["code-line-no"] }, [
                      { type: "text", value: String(i + 1) },
                    ]),
                  ],
                )
              : lineCopyButton(i + 1),
          );
        });
        addClass(pre, "has-line-numbers");
      }

      const label = LANG_LABELS[language] ?? language;

      const figure = el(
        "figure",
        { className: ["lab-code"], "data-lang": language },
        [
          el("figcaption", { className: ["lab-code-head"] }, [
            el("span", { className: ["lab-code-title"] }, [
              { type: "text", value: title ?? label },
            ]),
            // With a filename shown, the language becomes the secondary label.
            ...(title
              ? [
                  el("span", { className: ["lab-code-lang"] }, [
                    { type: "text", value: label },
                  ]),
                ]
              : []),
            blockCopyButton(),
          ]),
          pre,
        ],
      );

      // The figure stands in for the fence, so it inherits where the fence was
      // written. Nothing built here has a position of its own, and the editor's
      // preview needs one on the outermost node to scroll a block into view.
      figure.position = node.position;
      parent.children[index] = figure;

      // Children were replaced wholesale; there is nothing inside to visit.
      return "skip";
    });
  };
}

/**
 * Add a class to an element that already has some.
 *
 * Fussier than it looks. Shiki writes its classes under the property key
 * `class`, while hast's own convention is `className` — and the serialiser maps
 * *both* to a `class` attribute. Setting the one Shiki did not use produces an
 * element with two `class` attributes, of which the browser honours the first
 * and silently drops the second. So whichever key is already there is the one
 * that gets extended.
 */
function addClass(node: Element, name: string): void {
  const key = "className" in node.properties ? "className" : "class";
  const current = node.properties[key];

  const existing: string[] = (
    Array.isArray(current)
      ? current.map(String)
      : typeof current === "string"
        ? current.split(" ")
        : []
  ).filter(Boolean);

  if (existing.includes(name)) return;

  // hast types `className` as a list and any other key as a scalar; both
  // serialise to the same attribute.
  if (key === "className") node.properties.className = [...existing, name];
  else node.properties.class = [...existing, name].join(" ");
}

/* ------------------------------------------------------------------ *
 * Collapsible sections, part two
 * ------------------------------------------------------------------ */

/**
 * The disclosure arrow. Inline for the same reason the clipboard is: this is
 * hast built on the server, where a React icon component is not available.
 *
 * It points right when closed and is rotated by CSS when open, so the open and
 * closed states are one glyph rather than two that have to be kept in step.
 */
function chevron(): Element {
  return el(
    "svg",
    {
      "aria-hidden": "true",
      viewBox: "0 0 24 24",
      fill: "none",
      stroke: "currentColor",
      strokeWidth: "2",
      strokeLinecap: "round",
      strokeLinejoin: "round",
      className: ["lab-details-chevron"],
    },
    [el("path", { d: "M9 6l6 6-6 6" })],
  );
}

/**
 * Dress the `<details>` blocks that `remarkDetails` built.
 *
 * Split from that plugin because classes are not in the sanitiser's schema for
 * either tag — anything set before it runs is stripped back off. So the tags go
 * through sanitisation bare, and the decoration is added here, on the trusted
 * side, alongside the code blocks.
 *
 * Every `details` in the tree is one of ours: raw HTML never survives the
 * parse, so the directive is the only thing that can produce the element. The
 * summary is still looked up rather than assumed to be the first child.
 *
 * The body is wrapped because the section needs one padded box under the
 * heading, and because `.lab-prose`'s spacing rule only reaches its own direct
 * children — an unwrapped body would set solid.
 */
function rehypeDetails() {
  return (tree: Root) => {
    visit(tree, "element", (node: Element) => {
      if (node.tagName !== "details") return;

      const summary = node.children.find((c): c is Element =>
        isElement(c, "summary"),
      );
      if (!summary) return;

      addClass(node, "lab-details");
      addClass(summary, "lab-details-summary");
      summary.children = [
        chevron(),
        el("span", { className: ["lab-details-title"] }, summary.children),
      ];

      const body = node.children.filter((c) => c !== summary);
      node.children = [
        summary,
        // An empty section is a heading and nothing else; a wrapper there would
        // draw a rule under it with a padded void beneath.
        ...(body.length > 0
          ? [el("div", { className: ["lab-details-body"] }, body)]
          : []),
      ];
    });
  };
}

/* ------------------------------------------------------------------ *
 * Headings and links
 * ------------------------------------------------------------------ */

/**
 * Give every h2/h3 a stable id and collect them for the page's contents list.
 *
 * The slugger is created per document rather than per plugin instance: it
 * remembers what it has already issued so a guide with two "Verify" sections
 * gets `verify` and `verify-1`, and a shared one would carry that state across
 * unrelated guides.
 */
function rehypeHeadings() {
  return (tree: Root, file: { data: Record<string, unknown> }) => {
    const slugger = new GithubSlugger();
    const toc: TocEntry[] = [];

    visit(tree, "element", (node: Element) => {
      if (node.tagName !== "h2" && node.tagName !== "h3") return;

      const text = toString(node);
      const id =
        typeof node.properties.id === "string" && node.properties.id.length > 0
          ? node.properties.id
          : slugger.slug(text || "section");

      node.properties.id = id;
      // The whole heading is the anchor, so the target is as big as the words
      // rather than a link icon that has to be hunted for on hover.
      node.children = [
        el("a", { href: `#${id}`, className: ["heading-anchor"] }, node.children),
      ];

      toc.push({ id, text, depth: node.tagName === "h2" ? 2 : 3 });
    });

    file.data.toc = toc;
  };
}

/**
 * Send off-site links to a new tab. `noopener` is the point — `noreferrer` for
 * the same reason it always is — since a guide is a public page and the link
 * target is whatever a manager typed.
 */
function rehypeExternalLinks() {
  return (tree: Root) => {
    visit(tree, "element", (node: Element) => {
      if (node.tagName !== "a") return;
      const href = node.properties.href;
      if (typeof href !== "string" || !/^https?:\/\//i.test(href)) return;

      node.properties.target = "_blank";
      node.properties.rel = ["noopener", "noreferrer"];
    });
  };
}

/* ------------------------------------------------------------------ *
 * Source positions
 * ------------------------------------------------------------------ */

/**
 * The blocks worth pointing back at their source line.
 *
 * Block-level only: an anchor or a run of bold text starts somewhere in the
 * middle of a line, and a mapping that fine buys nothing — the finest thing
 * anyone can scroll to is the paragraph it sits in. `li` and `tr` are in the
 * list on purpose, since a long list or table is otherwise a single landmark
 * covering a screenful of source.
 */
const LINE_MARKED_TAGS = new Set([
  "p",
  "h1",
  "h2",
  "h3",
  "h4",
  "h5",
  "h6",
  "ul",
  "ol",
  "li",
  "blockquote",
  "pre",
  "figure",
  // A collapsible section marks both: the summary is what is on screen while
  // it is shut, and the section itself is the landmark once it is open.
  "details",
  "summary",
  "table",
  "thead",
  "tbody",
  "tr",
  "hr",
  "dl",
  "dt",
  "dd",
]);

/**
 * Record the source line each block came from, as `data-line`.
 *
 * Only the editor's preview asks for this: it is what lets the split view
 * scroll the rendered side to the part of the guide being typed. A published
 * page has no markdown to line up against, so it renders without the
 * attributes rather than carrying a few hundred of them for nobody.
 *
 * Runs last, after the code blocks have been rebuilt — a fence's `figure` is
 * generated markup that carries the fence's position forward by hand, and
 * everything Shiki puts inside it has no position at all, so the block gets one
 * mark on the outside instead of one per highlighted line.
 */
function rehypeSourceLines() {
  return (tree: Root) => {
    visit(tree, "element", (node: Element) => {
      const line = node.position?.start.line;
      if (line === undefined || !LINE_MARKED_TAGS.has(node.tagName)) return;
      node.properties["data-line"] = String(line);
    });
  };
}

/* ------------------------------------------------------------------ *
 * The pipeline
 * ------------------------------------------------------------------ */

const buildProcessor = (highlighter: Highlighter, sourceLines: boolean) => {
  const processor = unified()
    .use(remarkParse)
    .use(remarkGfm)
    .use(remarkDirective)
    .use(remarkDetails)
    .use(remarkRehype)
    .use(rehypeCarryCodeTitle)
    // GitHub's default rules, which already keep `language-*` on a code
    // element — `language-hcl:main.tf` included, which is what lets the fence
    // title survive this step — and which allow `details` and `summary`, which
    // is what lets a collapsible section through with its contents sanitised.
    .use(rehypeSanitize)
    // Everything below this line generates trusted markup.
    .use(rehypeHighlight, highlighter)
    .use(rehypeDetails)
    .use(rehypeHeadings)
    .use(rehypeExternalLinks);

  if (sourceLines) processor.use(rehypeSourceLines);

  return processor.use(rehypeStringify);
};

/**
 * The pipelines, built once each. Plugins hold no per-document state — the one
 * that would, the heading slugger, creates its own inside the transform — so a
 * single processor is safe to share across concurrent requests.
 *
 * Two of them, keyed by whether the output carries source lines: the flag
 * changes the plugin list, and the only alternative is rebuilding the pipeline
 * (and with it the reference to the highlighter) per request.
 */
const processors = new Map<
  boolean,
  Promise<ReturnType<typeof buildProcessor>>
>();

function getProcessor(sourceLines: boolean) {
  let processor = processors.get(sourceLines);
  if (!processor) {
    processor = getHighlighter().then((h) => buildProcessor(h, sourceLines));
    processors.set(sourceLines, processor);
  }
  return processor;
}

/** Render a guide body to HTML, with the headings it turned out to have. */
export async function renderMarkdown(
  markdown: string,
  {
    /**
     * Mark each block with the source line it came from, for an editor that
     * wants to line the rendering up against the markdown it was typed from.
     */
    sourceLines = false,
  }: { sourceLines?: boolean } = {},
): Promise<RenderedMarkdown> {
  if (markdown.trim().length === 0) return { html: "", toc: [] };

  const processor = await getProcessor(sourceLines);
  // Before anything parses it, so `remarkDetails` — which reads offsets back
  // out of the source it was given — and `data-line` both describe the same
  // text. The pass never adds or removes a line, so the numbers still point at
  // the markdown the author is looking at.
  const file = await processor.process(normaliseListIndents(markdown));

  return {
    html: String(file),
    toc: (file.data as { toc?: TocEntry[] }).toc ?? [],
  };
}
