import "server-only";

import GithubSlugger from "github-slugger";
import type { Element, ElementContent, Root, RootContent } from "hast";
import { toString } from "hast-util-to-string";
import type {
  BlockContent,
  DefinitionContent,
  Paragraph,
  Root as MdastRoot,
} from "mdast";
import rehypeSanitize, { defaultSchema } from "rehype-sanitize";
import rehypeStringify from "rehype-stringify";
import remarkDirective from "remark-directive";
import remarkGfm from "remark-gfm";
import remarkParse from "remark-parse";
import remarkRehype from "remark-rehype";
import { createHighlighter, type Highlighter } from "shiki";
import { unified } from "unified";
import { SKIP, visit } from "unist-util-visit";

/**
 * Markdown → HTML for lab guides.
 *
 * All of this runs on the server and ships zero markdown code to the browser:
 * a guide is read far more often than it is written, and the reader should not
 * pay to parse a document that was already parsed. The one client-side piece is
 * the copy buttons (`@/components/lab-guide-body`), which attach to markup
 * generated here.
 *
 * Two rules the pipeline order encodes:
 *
 *  1. Raw HTML in the source is dropped, not rendered — `remark-rehype` ignores
 *     it unless `allowDangerousHtml` is set, and it is not set. Authors write
 *     Markdown; they do not get an HTML injection point into a public page.
 *  2. `rehype-sanitize` runs on the author's tree and nothing else. Everything
 *     added afterwards — heading ids, link rels, the entire highlighted code
 *     block — is generated by this file, so sanitising it again would only
 *     strip our own attributes back off.
 */

/** A heading the guide page can build an "on this page" list from. */
export type TocEntry = { id: string; text: string; depth: 2 | 3 };

export type RenderedMarkdown = { html: string; toc: TocEntry[] };

/**
 * Themes for the two colour schemes. Only their *foreground* tokens are used —
 * `globals.css` paints the block with the app's own surface colours, so a code
 * block never arrives with a background that a theme happened to pick.
 */
const THEMES = { light: "github-light-default", dark: "github-dark-default" };

/**
 * Grammars loaded up front. Deliberately a fixed list rather than
 * load-on-demand: a lab guide is rendered inside a request, and a cache miss
 * that has to fetch a grammar mid-render is a stall on the reader's page. This
 * is the set a cloud workshop actually writes — shells, config, IaC, and the
 * handful of languages the exercises are in.
 *
 * An unknown language falls back to unhighlighted text rather than throwing;
 * see `languageFor`.
 */
const LANGS = [
  "bash",
  "shellsession",
  "json",
  "jsonc",
  "yaml",
  "hcl",
  "terraform",
  "typescript",
  "javascript",
  "tsx",
  "python",
  "go",
  "java",
  "groovy",
  "sql",
  "dockerfile",
  "diff",
  "markdown",
  "html",
  "css",
  "xml",
  "toml",
  "ini",
  "powershell",
];

/** How a language is named in the block's header, where it differs. */
const LANG_LABELS: Record<string, string> = {
  bash: "Shell",
  shellsession: "Shell session",
  hcl: "Terraform",
  terraform: "Terraform",
  tsx: "TSX",
  jsonc: "JSON",
  yaml: "YAML",
  json: "JSON",
  sql: "SQL",
  html: "HTML",
  css: "CSS",
  xml: "XML",
  toml: "TOML",
  ini: "INI",
  text: "Text",
};

/**
 * One highlighter per process, created on first use.
 *
 * Creating it loads every grammar above, so it is far too expensive to do per
 * request — and far too expensive to do at module load, which would put it on
 * the cold start of every page in the app rather than only the guides.
 */
let highlighterPromise: Promise<Highlighter> | null = null;

function getHighlighter(): Promise<Highlighter> {
  highlighterPromise ??= createHighlighter({
    themes: Object.values(THEMES),
    langs: LANGS,
  });
  return highlighterPromise;
}

const isElement = (node: RootContent, tagName: string): node is Element =>
  node.type === "element" && node.tagName === tagName;

/* ------------------------------------------------------------------ *
 * Code fence info strings
 * ------------------------------------------------------------------ */

/**
 * Carry a fence's title through sanitisation.
 *
 * ```` ```bash title="setup.sh" ```` puts "setup.sh" in the mdast node's meta,
 * which `rehype-sanitize` drops — it rebuilds every node from the attributes
 * its schema allows, and `data` is not an attribute. The class name *does*
 * survive (the default schema keeps `language-*` on `code`), so the title is
 * folded into it here and unpacked again on the other side.
 *
 * Encoded because a class attribute cannot contain spaces, and "Step 2 — main.tf"
 * is exactly the sort of title somebody will write.
 */
function rehypeCarryCodeTitle() {
  return (tree: Root) => {
    visit(tree, "element", (node: Element) => {
      if (node.tagName !== "code") return;

      const meta = (node.data as { meta?: string } | undefined)?.meta;
      if (!meta) return;

      const title = meta.match(/(?:^|\s)title=(?:"([^"]*)"|'([^']*)'|(\S+))/);
      const value = title?.[1] ?? title?.[2] ?? title?.[3];
      if (!value) return;

      const classes = Array.isArray(node.properties.className)
        ? node.properties.className
        : [];
      const lang = classes.find(
        (c) => typeof c === "string" && c.startsWith("language-"),
      );
      if (typeof lang !== "string") return;

      node.properties.className = classes.map((c) =>
        c === lang ? `${lang}:${encodeURIComponent(value)}` : c,
      );
    });
  };
}

/** The language and optional title a fence asked for. */
function parseInfo(code: Element): { lang: string; title: string | null } {
  const classes = Array.isArray(code.properties.className)
    ? code.properties.className
    : [];
  const marker = classes.find(
    (c): c is string => typeof c === "string" && c.startsWith("language-"),
  );
  if (!marker) return { lang: "text", title: null };

  const [lang, encoded] = marker.slice("language-".length).split(":", 2);
  let title: string | null = null;
  if (encoded) {
    try {
      title = decodeURIComponent(encoded);
    } catch {
      // A title that survived this far but won't decode isn't worth a 500.
      title = encoded;
    }
  }
  return { lang: lang.toLowerCase() || "text", title };
}

/* ------------------------------------------------------------------ *
 * List indentation
 * ------------------------------------------------------------------ */

/** A line that opens a list item: its indent, its marker, the gap after it. */
const LIST_ITEM = /^([ \t]*)([-*+]|\d{1,9}[.)])([ \t]+)(?=\S)/;

/** A fence, once the line's indent (and any list marker) is off the front. */
const FENCE = /^(`{3,}|~{3,})(.*)$/;

/** How far past a marker's own indent a line has to be to be inside the item. */
const CONTINUATION = 2;

/** Leading whitespace as a column, counting a tab to the next stop of four. */
function indentWidth(line: string): number {
  let width = 0;
  for (const ch of line) {
    if (ch === " ") width += 1;
    else if (ch === "\t") width += 4 - (width % 4);
    else break;
  }
  return width;
}

/** Move a line right, leaving blank lines blank. */
const shiftLine = (line: string, by: number): string =>
  by > 0 && line.trim().length > 0 ? " ".repeat(by) + line : line;

/**
 * Re-indent under-indented blocks so they stay in the list item they follow.
 *
 * Markdown keeps a block inside a list item only while it is indented to that
 * item's *content column* — three for `1. `, four for `10. `, two for `- `. A
 * fence or an image one space short of that closes the list instead, and the
 * steps below it become a second list numbered from one. Nothing about the
 * source shows it: two spaces looks indented, and the rule that two is enough
 * under a bullet but not under a number is not one anybody should have to hold
 * in their head while writing a lab.
 *
 * So the guides get one rule — two spaces means "still inside this step" — and
 * this pass turns that into whatever column the parser actually wants, before
 * the parser sees it. Indenting is all it does: a line is only ever moved
 * right, and only ever to the content column of the item it is already inside,
 * so a correctly indented guide passes through untouched.
 *
 * Line-for-line, deliberately. The editor's preview lines its scroll up against
 * `data-line`, and every one of those numbers comes from parsing what this
 * function returns — so it may change what a line starts with, but never how
 * many there are.
 *
 * Fenced code is copied through with the shift its opening fence got and
 * nothing else: a list marker is only a list marker in prose, and these guides
 * are full of YAML, whose every sequence entry would otherwise open an item and
 * drag the rest of the block in after it.
 */
function normaliseListIndents(markdown: string): string {
  const lines = markdown.split("\n");
  const out: string[] = [];

  /** The list items currently open, outermost first. */
  const open: { srcIndent: number; contentColumn: number }[] = [];
  /** The fence being copied through, if the walk is inside one. */
  let fence: { marker: string; by: number; floor: number } | null = null;

  for (const line of lines) {
    if (fence) {
      // Code keeps its shape relative to its fence, but no line may sit left
      // of the item's content column: a fence moved into a step takes its
      // contents with it, and a line short of that column would end the step —
      // closing the block early and spilling the rest of the code into the
      // page as prose.
      out.push(
        shiftLine(line, Math.max(fence.by, fence.floor - indentWidth(line))),
      );

      // A closing fence is the same character, at least as long, and alone on
      // its line — anything else is code that happens to start with backticks.
      const close = line.trim().match(FENCE);
      if (
        close &&
        close[1][0] === fence.marker[0] &&
        close[1].length >= fence.marker.length &&
        close[2].trim().length === 0
      ) {
        fence = null;
      }
      continue;
    }

    // A blank line separates blocks but does not end a list, so it neither
    // closes an item nor needs moving.
    if (line.trim().length === 0) {
      out.push(line);
      continue;
    }

    const width = indentWidth(line);

    // Anything not far enough in has left the items it is not far enough for.
    while (
      open.length > 0 &&
      width < open[open.length - 1].srcIndent + CONTINUATION
    ) {
      open.pop();
    }

    const item = open[open.length - 1];
    const by = item ? Math.max(0, item.contentColumn - width) : 0;
    out.push(shiftLine(line, by));

    const opened = line.match(LIST_ITEM);
    if (opened) {
      // Where this item's own content starts, in the output.
      const marker = opened[2].length + opened[3].length;
      open.push({ srcIndent: width, contentColumn: width + by + marker });
    }

    // A fence opens on its own line, or directly after a marker on the line
    // that opened the item.
    const rest = opened ? line.slice(opened[0].length) : line.trimStart();
    const start = rest.match(FENCE);
    if (start) {
      // A fence on a marker line belongs to the item that marker just opened.
      const inner = opened ? open[open.length - 1] : item;
      fence = { marker: start[1], by, floor: inner?.contentColumn ?? 0 };
    }
  }

  return out.join("\n");
}

/* ------------------------------------------------------------------ *
 * Callouts
 * ------------------------------------------------------------------ */

/**
 * The kinds of callout a guide can write, and the heading each falls back to
 * when it is opened without one.
 *
 * Five, deliberately. A palette of callouts only means anything while a reader
 * can tell them apart at a glance, and a guide with eight shades of tinted box
 * in it has none — every one of these has its own hue *and* its own glyph.
 *
 * `note` is the quiet one, in the palette's own slate: an aside that is worth
 * setting apart from the prose but is not a hazard. The other four are coloured
 * by what they cost the reader if ignored, which is why `danger` borrows
 * `--destructive` rather than introducing a second red.
 */
const CALLOUTS = {
  note: "Note",
  tip: "Tip",
  success: "Success",
  warning: "Warning",
  danger: "Caution",
} as const;

type CalloutKind = keyof typeof CALLOUTS;

/**
 * Other names for the same box.
 *
 * GitHub's alert syntax and Docusaurus's admonitions between them have taught
 * everybody a slightly different vocabulary, and a guide that says `:::caution`
 * meant a callout — not a paragraph beginning with three colons. Mapped rather
 * than added as kinds of their own so the rendering stays the five above.
 */
const CALLOUT_ALIASES: Record<string, CalloutKind> = {
  info: "note",
  important: "note",
  caution: "danger",
  error: "danger",
  warn: "warning",
  check: "success",
};

/** The callout kind a directive name asks for, if it asks for one. */
const calloutKind = (name: string): CalloutKind | null =>
  name in CALLOUTS
    ? (name as CalloutKind)
    : (CALLOUT_ALIASES[name] ?? null);

/* ------------------------------------------------------------------ *
 * Directive titles
 * ------------------------------------------------------------------ */

/** A block directive that takes a title: the callouts, plus `details`. */
const hasTitle = (name: string): boolean =>
  name === "details" || calloutKind(name) !== null;

/**
 * A directive opening with something other than a label after its name:
 * the indent, the name, and the rest of the line.
 */
const DIRECTIVE_OPEN = /^([ \t]*):{3,}([A-Za-z][A-Za-z\d-]*)[ \t]+(\S.*?)[ \t]*$/;

/**
 * Let a callout's title be written as plain text after its name.
 *
 * `remark-directive`'s own spelling puts the title in brackets —
 * `:::tip[Stop and smell the code]` — and a container directive whose opening
 * line has anything *else* on it is not a directive at all: the extension
 * declines it, and the whole block, closing `:::` included, lands in the page as
 * a paragraph of literal punctuation. That is a silent failure of exactly the
 * kind an author cannot debug, over a pair of brackets that carry no meaning of
 * their own.
 *
 * So both spellings are accepted, and this pass turns the loose one into the
 * strict one before anything parses it. Line-for-line, like
 * `normaliseListIndents` — `data-line` and the editor's preview scrolling both
 * depend on the line numbers surviving every pass.
 *
 * Only the names this renderer knows are rewritten. An unrecognised directive is
 * put back into the page as the text that was typed (see
 * `remarkBlockDirectives`), and it should read as what the author wrote rather
 * than as something this pass did to it on the way past.
 */
function normaliseDirectiveTitles(markdown: string): string {
  let fence: string | null = null;

  return markdown
    .split("\n")
    .map((line) => {
      // Three colons in a shell heredoc or a YAML block are not a directive.
      const marker = line.trim().match(FENCE);
      if (fence) {
        if (
          marker &&
          marker[1][0] === fence[0] &&
          marker[1].length >= fence.length &&
          marker[2].trim().length === 0
        ) {
          fence = null;
        }
        return line;
      }
      if (marker) {
        fence = marker[1];
        return line;
      }

      const open = line.match(DIRECTIVE_OPEN);
      if (!open || !hasTitle(open[2].toLowerCase())) return line;

      // Already in the strict form, give or take a space — `:::tip [a]` or
      // `:::details[x] {open}`. Nothing to do, and guessing would break it.
      const rest = open[3];
      if (rest.startsWith("[") || rest.startsWith("{")) return line;

      // The title becomes the contents of a bracketed label, so its own
      // brackets have to stop being label syntax.
      const label = rest.replace(/[[\]\\]/g, "\\$&");
      return `${open[1]}:::${open[2]}[${label}]`;
    })
    .join("\n");
}

/* ------------------------------------------------------------------ *
 * Collapsible sections
 * ------------------------------------------------------------------ */

/** The heading on a collapsible section that was opened without one. */
const DEFAULT_SUMMARY = "Details";

/** What a container directive may hold, which is anything a document may. */
type DirectiveContent = BlockContent | DefinitionContent;

/**
 * The title a directive was opened with, taken off the front of its body.
 *
 * `:::details[Show the answer]` puts the label in a leading paragraph, flagged
 * as such. Without one the block still needs a heading — a collapsible section
 * with a blank summary is an unlabelled strip you have to click to identify —
 * so the caller's fallback stands in.
 */
function directiveTitle(
  children: DirectiveContent[],
  fallback: string,
): { title: Paragraph; body: DirectiveContent[] } {
  const [first] = children;
  const labelled =
    first?.type === "paragraph" &&
    (first.data as { directiveLabel?: boolean } | undefined)
      ?.directiveLabel === true;

  return labelled
    ? { title: first, body: children.slice(1) }
    : {
        title: {
          type: "paragraph",
          children: [{ type: "text", value: fallback }],
        },
        body: children,
      };
}

/**
 * `:::` blocks → the two structures a guide is allowed to build with them.
 *
 * Directives rather than raw HTML, because raw HTML never reaches the output:
 * `remark-rehype` runs without `allowDangerousHtml`, and that stays true — a
 * guide body is not an HTML injection point. `remark-directive` adds one generic
 * block syntax instead, and this plugin decides what it may mean:
 *
 *  - `:::details[Show the answer]` … `:::` → a `<details>` block, expanded from
 *    the start if it was opened `:::details[Title]{open}`;
 *  - `:::tip[Stop and smell the code]` … `:::` → a callout, in any of the kinds
 *    in `CALLOUTS`.
 *
 * Both are built *here*, before sanitisation, rather than afterwards like the
 * code blocks. The tags they need — `details`, `summary`, `div`, `p` — are ones
 * the schema already allows, and building them in mdast means the title and the
 * body are ordinary Markdown that gets sanitised along with everything else. Only
 * the decoration — classes, the chevron, the icon, the body wrapper — is added on
 * the trusted side, in `rehypeDetails` and `rehypeCallouts`.
 *
 * Everything else the syntax can match is put back as the text that was typed.
 * That is the whole reason this runs as one pass over every directive node:
 * turning the extension on also makes `:name` a directive *mid-sentence*, so a
 * guide that says `key:value` — and these guides are full of that — would
 * otherwise lose the second half of the word. Directives are a feature of this
 * one block form; anywhere else the punctuation means what it looks like.
 */
function remarkBlockDirectives() {
  return (tree: MdastRoot, file: { value: unknown }) => {
    const source = String(file.value);

    visit(tree, (node, index, parent) => {
      if (
        node.type !== "containerDirective" &&
        node.type !== "leafDirective" &&
        node.type !== "textDirective"
      ) {
        return;
      }

      const kind =
        node.type === "containerDirective" ? calloutKind(node.name) : null;

      if (
        node.type !== "containerDirective" ||
        (node.name !== "details" && kind === null)
      ) {
        const start = node.position?.start.offset;
        const end = node.position?.end.offset;
        if (!parent || index === undefined || start === undefined || end === undefined) {
          return SKIP;
        }

        parent.children[index] = {
          type: "text",
          value: source.slice(start, end),
          position: node.position,
        };
        // The node is detached; its children are not part of the document.
        return SKIP;
      }

      if (kind !== null) {
        // The heading is always present, so what survives sanitisation is a
        // shape `rehypeCallouts` can read without guessing: the first paragraph
        // in the box is its title, and everything after it is the body.
        const { title, body } = directiveTitle(node.children, CALLOUTS[kind]);

        node.children = [title, ...body];
        node.data = {
          ...node.data,
          hName: "div",
          // The kind has to reach the far side of the sanitiser to be styled,
          // and a class would not: see `SANITIZE_SCHEMA`.
          hProperties: { "data-callout": kind },
        };
        return;
      }

      const { title: summary, body } = directiveTitle(
        node.children,
        DEFAULT_SUMMARY,
      );
      summary.data = { ...summary.data, hName: "summary" };

      node.children = [summary, ...body];
      node.data = {
        ...node.data,
        hName: "details",
        hProperties: { open: node.attributes?.open !== undefined },
      };
    });
  };
}

/* ------------------------------------------------------------------ *
 * Code blocks
 * ------------------------------------------------------------------ */

const el = (
  tagName: string,
  properties: Element["properties"],
  children: ElementContent[] = [],
): Element => ({ type: "element", tagName, properties, children });

/**
 * The clipboard glyph, inline rather than from `lucide-react` — this markup is
 * built as hast on the server, where a React component is not available. The
 * "copied" tick is a sibling; `globals.css` swaps which one is visible.
 *
 * `data-nocopy` marks everything that is chrome rather than code: the copy
 * handler strips these before reading the text, so the buttons and the line
 * numbers never end up on the clipboard.
 */
function icon(kind: "clipboard" | "check"): Element {
  const paths =
    kind === "clipboard"
      ? [
          "M9 4h6a1 1 0 0 1 1 1v1H8V5a1 1 0 0 1 1-1z",
          "M8 6H6a2 2 0 0 0-2 2v11a2 2 0 0 0 2 2h12a2 2 0 0 0 2-2V8a2 2 0 0 0-2-2h-2",
        ]
      : ["M5 13l4 4L19 7"];

  return el(
    "svg",
    {
      "aria-hidden": "true",
      viewBox: "0 0 24 24",
      fill: "none",
      stroke: "currentColor",
      strokeWidth: "2",
      strokeLinecap: "round",
      strokeLinejoin: "round",
      className: [`code-icon`, `code-icon-${kind}`],
    },
    paths.map((d) => el("path", { d })),
  );
}

/** Copy the whole block. Lives in the block header, always visible. */
function blockCopyButton(): Element {
  return el(
    "button",
    {
      type: "button",
      className: ["code-copy"],
      "data-copy": "block",
      "data-nocopy": "true",
      "aria-label": "Copy code",
    },
    [
      icon("clipboard"),
      icon("check"),
      el("span", { className: ["code-copy-label"] }, [
        { type: "text", value: "Copy" },
      ]),
      el("span", { className: ["code-copy-done"] }, [
        { type: "text", value: "Copied" },
      ]),
    ],
  );
}

/**
 * The per-line control: a line number that turns into a copy button.
 *
 * Doubling the two is deliberate. A gutter of numbers is worth having on its
 * own — half of running a lab is somebody saying "the export on line 4" — and
 * hanging the copy affordance off it means a line costs one control instead of
 * two, with nothing hovering over the code until the pointer is on that line.
 */
function lineCopyButton(lineNumber: number): Element {
  return el(
    "button",
    {
      type: "button",
      className: ["code-line-copy"],
      "data-copy": "line",
      "data-nocopy": "true",
      tabIndex: -1,
      "aria-label": `Copy line ${lineNumber}`,
      title: `Copy line ${lineNumber}`,
    },
    [
      el("span", { className: ["code-line-no"] }, [
        { type: "text", value: String(lineNumber) },
      ]),
      icon("clipboard"),
      icon("check"),
    ],
  );
}

/**
 * Replace every ```<pre><code>``` with a highlighted, copyable block.
 *
 * Runs after sanitisation, so everything it builds is trusted by construction:
 * the only author-supplied value that survives into the output is the code
 * text itself, which Shiki tokenises into text nodes.
 */
function rehypeHighlight(highlighter: Highlighter) {
  const loaded = new Set(highlighter.getLoadedLanguages());

  return (tree: Root) => {
    visit(tree, "element", (node: Element, index, parent) => {
      if (node.tagName !== "pre" || !parent || index === undefined) return;

      const code = node.children.find((c) => isElement(c, "code"));
      if (!code || code.type !== "element") return;

      const { lang, title } = parseInfo(code);
      const language = loaded.has(lang) ? lang : "text";
      // Markdown fences always end in a newline; keeping it would render an
      // empty final line, complete with its own line number.
      const source = toString(code).replace(/\n$/, "");

      const highlighted = highlighter.codeToHast(source, {
        lang: language,
        themes: THEMES,
        // Emit both themes as CSS variables instead of picking one at render
        // time. The server has no idea which scheme the reader is in — the
        // theme is applied by a class on <html> in the browser — so the block
        // has to carry both and let CSS choose.
        defaultColor: false,
      });

      const pre = highlighted.children.find(
        (c): c is Element => c.type === "element" && c.tagName === "pre",
      );
      if (!pre) return;

      const codeEl = pre.children.find(
        (c): c is Element => c.type === "element" && c.tagName === "code",
      );

      // Shiki separates its line spans with literal newlines, which is how a
      // `<pre>` normally breaks them. These lines are laid out as blocks
      // instead — a block is what gives the line gutter something to stick to —
      // so those newlines would each open a second, empty line box and double
      // the leading. Dropping them here means the *rendered* text no longer
      // carries the line breaks, which is why the copy handler rebuilds them
      // from the line elements rather than reading `textContent`.
      if (codeEl) {
        codeEl.children = codeEl.children.filter(
          (c) => !(c.type === "text" && c.value.trim().length === 0),
        );
      }

      // Number every line, but only when there is more than one: a single
      // shell command is not a listing, and a lone "1" beside it is noise the
      // block's own copy button already covers.
      const lines =
        codeEl?.children.filter(
          (c): c is Element =>
            c.type === "element" &&
            typeof c.properties?.class === "string" &&
            c.properties.class.split(" ").includes("line"),
        ) ?? [];

      if (lines.length > 1) {
        lines.forEach((line, i) => {
          // Blank lines get a number for alignment but nothing to copy.
          const blank = toString(line).trim().length === 0;
          line.children.unshift(
            blank
              ? el(
                  "span",
                  {
                    className: ["code-line-copy", "is-blank"],
                    "data-nocopy": "true",
                    "aria-hidden": "true",
                  },
                  [
                    el("span", { className: ["code-line-no"] }, [
                      { type: "text", value: String(i + 1) },
                    ]),
                  ],
                )
              : lineCopyButton(i + 1),
          );
        });
        addClass(pre, "has-line-numbers");
      }

      const label = LANG_LABELS[language] ?? language;

      const figure = el(
        "figure",
        { className: ["lab-code"], "data-lang": language },
        [
          el("figcaption", { className: ["lab-code-head"] }, [
            el("span", { className: ["lab-code-title"] }, [
              { type: "text", value: title ?? label },
            ]),
            // With a filename shown, the language becomes the secondary label.
            ...(title
              ? [
                  el("span", { className: ["lab-code-lang"] }, [
                    { type: "text", value: label },
                  ]),
                ]
              : []),
            blockCopyButton(),
          ]),
          pre,
        ],
      );

      // The figure stands in for the fence, so it inherits where the fence was
      // written. Nothing built here has a position of its own, and the editor's
      // preview needs one on the outermost node to scroll a block into view.
      figure.position = node.position;
      parent.children[index] = figure;

      // Children were replaced wholesale; there is nothing inside to visit.
      return "skip";
    });
  };
}

/**
 * Add a class to an element that already has some.
 *
 * Fussier than it looks. Shiki writes its classes under the property key
 * `class`, while hast's own convention is `className` — and the serialiser maps
 * *both* to a `class` attribute. Setting the one Shiki did not use produces an
 * element with two `class` attributes, of which the browser honours the first
 * and silently drops the second. So whichever key is already there is the one
 * that gets extended.
 */
function addClass(node: Element, name: string): void {
  const key = "className" in node.properties ? "className" : "class";
  const current = node.properties[key];

  const existing: string[] = (
    Array.isArray(current)
      ? current.map(String)
      : typeof current === "string"
        ? current.split(" ")
        : []
  ).filter(Boolean);

  if (existing.includes(name)) return;

  // hast types `className` as a list and any other key as a scalar; both
  // serialise to the same attribute.
  if (key === "className") node.properties.className = [...existing, name];
  else node.properties.class = [...existing, name].join(" ");
}

/* ------------------------------------------------------------------ *
 * Collapsible sections, part two
 * ------------------------------------------------------------------ */

/**
 * The disclosure arrow. Inline for the same reason the clipboard is: this is
 * hast built on the server, where a React icon component is not available.
 *
 * It points right when closed and is rotated by CSS when open, so the open and
 * closed states are one glyph rather than two that have to be kept in step.
 */
function chevron(): Element {
  return el(
    "svg",
    {
      "aria-hidden": "true",
      viewBox: "0 0 24 24",
      fill: "none",
      stroke: "currentColor",
      strokeWidth: "2",
      strokeLinecap: "round",
      strokeLinejoin: "round",
      className: ["lab-details-chevron"],
    },
    [el("path", { d: "M9 6l6 6-6 6" })],
  );
}

/**
 * Dress the `<details>` blocks that `remarkBlockDirectives` built.
 *
 * Split from that plugin because classes are not in the sanitiser's schema for
 * either tag — anything set before it runs is stripped back off. So the tags go
 * through sanitisation bare, and the decoration is added here, on the trusted
 * side, alongside the code blocks.
 *
 * Every `details` in the tree is one of ours: raw HTML never survives the
 * parse, so the directive is the only thing that can produce the element. The
 * summary is still looked up rather than assumed to be the first child.
 *
 * The body is wrapped because the section needs one padded box under the
 * heading, and because `.lab-prose`'s spacing rule only reaches its own direct
 * children — an unwrapped body would set solid.
 */
function rehypeDetails() {
  return (tree: Root) => {
    visit(tree, "element", (node: Element) => {
      if (node.tagName !== "details") return;

      const summary = node.children.find((c): c is Element =>
        isElement(c, "summary"),
      );
      if (!summary) return;

      addClass(node, "lab-details");
      addClass(summary, "lab-details-summary");
      summary.children = [
        chevron(),
        el("span", { className: ["lab-details-title"] }, summary.children),
      ];

      const body = node.children.filter((c) => c !== summary);
      node.children = [
        summary,
        // An empty section is a heading and nothing else; a wrapper there would
        // draw a rule under it with a padded void beneath.
        ...(body.length > 0
          ? [el("div", { className: ["lab-details-body"] }, body)]
          : []),
      ];
    });
  };
}

/* ------------------------------------------------------------------ *
 * Callouts, part two
 * ------------------------------------------------------------------ */

/**
 * The glyph each kind of callout is marked with, as hast.
 *
 * Lucide's own path data, so a callout is drawn from the same set as every other
 * icon in the app, but written out here because this markup is generated on the
 * server where a React component is not one of the options — the same reason the
 * clipboard and the chevron above are inline.
 *
 * Factories rather than shared nodes: a hast node is a mutable object, and two
 * documents rendering at once must not be handed the same one.
 *
 * `tip` takes the ⓘ rather than the lightbulb it has elsewhere, because that is
 * the glyph on the callout these were specified from.
 */
const CALLOUT_ICONS: Record<CalloutKind, () => ElementContent[]> = {
  note: () => [
    el("path", {
      d: "M21.174 6.812a1 1 0 0 0-3.986-3.987L3.842 16.174a2 2 0 0 0-.5.83l-1.321 4.352a.5.5 0 0 0 .623.622l4.353-1.32a2 2 0 0 0 .83-.497z",
    }),
    el("path", { d: "m15 5 4 4" }),
  ],
  tip: () => [
    el("circle", { cx: "12", cy: "12", r: "10" }),
    el("path", { d: "M12 16v-4" }),
    el("path", { d: "M12 8h.01" }),
  ],
  success: () => [
    el("circle", { cx: "12", cy: "12", r: "10" }),
    el("path", { d: "m9 12 2 2 4-4" }),
  ],
  warning: () => [
    el("path", {
      d: "m21.73 18-8-14a2 2 0 0 0-3.48 0l-8 14A2 2 0 0 0 4 21h16a2 2 0 0 0 1.73-3",
    }),
    el("path", { d: "M12 9v4" }),
    el("path", { d: "M12 17h.01" }),
  ],
  danger: () => [
    el("path", {
      d: "M15.312 2a2 2 0 0 1 1.414.586l4.688 4.688A2 2 0 0 1 22 8.688v6.624a2 2 0 0 1-.586 1.414l-4.688 4.688a2 2 0 0 1-1.414.586H8.688a2 2 0 0 1-1.414-.586l-4.688-4.688A2 2 0 0 1 2 15.312V8.688a2 2 0 0 1 .586-1.414l4.688-4.688A2 2 0 0 1 8.688 2z",
    }),
    el("path", { d: "M12 8v4" }),
    el("path", { d: "M12 16h.01" }),
  ],
};

function calloutIcon(kind: CalloutKind): Element {
  return el(
    "svg",
    {
      "aria-hidden": "true",
      viewBox: "0 0 24 24",
      fill: "none",
      stroke: "currentColor",
      strokeWidth: "2",
      strokeLinecap: "round",
      strokeLinejoin: "round",
      className: ["lab-callout-icon"],
    },
    CALLOUT_ICONS[kind](),
  );
}

/**
 * Dress the callouts that `remarkBlockDirectives` built.
 *
 * Here rather than in that plugin for the same reason `<details>` is dressed
 * here: a class on a `div` is not in the sanitiser's schema, so anything set
 * before it runs is stripped straight back off. The one thing that *does* come
 * through is `data-callout`, which is what this pass reads the kind from — and
 * the kind was chosen from a closed set on the way in, so what arrives here is
 * one of five words rather than anything an author typed.
 *
 * The heading is the box's first paragraph, always present by construction. The
 * body is wrapped so it can be spaced as a document of its own: `.lab-prose`'s
 * rhythm rule only reaches its own direct children, and a callout two paragraphs
 * long would otherwise set solid.
 */
function rehypeCallouts() {
  return (tree: Root) => {
    visit(tree, "element", (node: Element) => {
      if (node.tagName !== "div") return;

      const kind = node.properties["data-callout"];
      if (typeof kind !== "string" || !(kind in CALLOUTS)) return;

      const head = node.children.find((c): c is Element => isElement(c, "p"));
      if (!head) return;

      addClass(node, "lab-callout");
      addClass(head, "lab-callout-head");
      head.children = [
        calloutIcon(kind as CalloutKind),
        el("span", { className: ["lab-callout-title"] }, head.children),
      ];

      const body = node.children.filter((c) => c !== head);
      node.children = [
        head,
        // A callout can be a heading and nothing else — a one-line aside whose
        // title says all of it — and a wrapper there would pad out a void.
        ...(body.some((c) => c.type !== "text" || c.value.trim().length > 0)
          ? [el("div", { className: ["lab-callout-body"] }, body)]
          : []),
      ];
    });
  };
}

/* ------------------------------------------------------------------ *
 * Headings and links
 * ------------------------------------------------------------------ */

/**
 * Give every h2/h3 a stable id and collect them for the page's contents list.
 *
 * The slugger is created per document rather than per plugin instance: it
 * remembers what it has already issued so a guide with two "Verify" sections
 * gets `verify` and `verify-1`, and a shared one would carry that state across
 * unrelated guides.
 */
function rehypeHeadings() {
  return (tree: Root, file: { data: Record<string, unknown> }) => {
    const slugger = new GithubSlugger();
    const toc: TocEntry[] = [];

    visit(tree, "element", (node: Element) => {
      if (node.tagName !== "h2" && node.tagName !== "h3") return;

      const text = toString(node);
      const id =
        typeof node.properties.id === "string" && node.properties.id.length > 0
          ? node.properties.id
          : slugger.slug(text || "section");

      node.properties.id = id;
      // The whole heading is the anchor, so the target is as big as the words
      // rather than a link icon that has to be hunted for on hover.
      node.children = [
        el("a", { href: `#${id}`, className: ["heading-anchor"] }, node.children),
      ];

      toc.push({ id, text, depth: node.tagName === "h2" ? 2 : 3 });
    });

    file.data.toc = toc;
  };
}

/**
 * Send off-site links to a new tab. `noopener` is the point — `noreferrer` for
 * the same reason it always is — since a guide is a public page and the link
 * target is whatever a manager typed.
 */
function rehypeExternalLinks() {
  return (tree: Root) => {
    visit(tree, "element", (node: Element) => {
      if (node.tagName !== "a") return;
      const href = node.properties.href;
      if (typeof href !== "string" || !/^https?:\/\//i.test(href)) return;

      node.properties.target = "_blank";
      node.properties.rel = ["noopener", "noreferrer"];
    });
  };
}

/* ------------------------------------------------------------------ *
 * Source positions
 * ------------------------------------------------------------------ */

/**
 * The blocks worth pointing back at their source line.
 *
 * Block-level only: an anchor or a run of bold text starts somewhere in the
 * middle of a line, and a mapping that fine buys nothing — the finest thing
 * anyone can scroll to is the paragraph it sits in. `li` and `tr` are in the
 * list on purpose, since a long list or table is otherwise a single landmark
 * covering a screenful of source.
 */
const LINE_MARKED_TAGS = new Set([
  "p",
  "h1",
  "h2",
  "h3",
  "h4",
  "h5",
  "h6",
  "ul",
  "ol",
  "li",
  "blockquote",
  "pre",
  "figure",
  // A collapsible section marks both: the summary is what is on screen while
  // it is shut, and the section itself is the landmark once it is open.
  "details",
  "summary",
  // The only `div` with a position of its own is a callout: nothing else in the
  // pipeline emits one from the source, and the wrappers built afterwards have
  // no position to mark.
  "div",
  "table",
  "thead",
  "tbody",
  "tr",
  "hr",
  "dl",
  "dt",
  "dd",
]);

/**
 * Record the source line each block came from, as `data-line`.
 *
 * Only the editor's preview asks for this: it is what lets the split view
 * scroll the rendered side to the part of the guide being typed. A published
 * page has no markdown to line up against, so it renders without the
 * attributes rather than carrying a few hundred of them for nobody.
 *
 * Runs last, after the code blocks have been rebuilt — a fence's `figure` is
 * generated markup that carries the fence's position forward by hand, and
 * everything Shiki puts inside it has no position at all, so the block gets one
 * mark on the outside instead of one per highlighted line.
 */
function rehypeSourceLines() {
  return (tree: Root) => {
    visit(tree, "element", (node: Element) => {
      const line = node.position?.start.line;
      if (line === undefined || !LINE_MARKED_TAGS.has(node.tagName)) return;
      node.properties["data-line"] = String(line);
    });
  };
}

/* ------------------------------------------------------------------ *
 * The pipeline
 * ------------------------------------------------------------------ */

/**
 * GitHub's rules, plus the one attribute this renderer needs to survive them.
 *
 * `data-callout` is how a callout's kind reaches the far side of the sanitiser,
 * where the box is dressed (`rehypeCallouts`). A class would not get there —
 * `div` has none in the schema — and the trick the fence titles use, folding the
 * value into a `language-*` class, has no equivalent on a `div`.
 *
 * Widening the schema is safe here in a way it would not usually be: the only
 * `div` in the tree at this point is one `remarkBlockDirectives` built, since raw
 * HTML never survives the parse, and the value is one of five words that plugin
 * chose from a closed set. The list is spelled out anyway, so an attribute that
 * somehow arrives holding anything else is dropped rather than trusted.
 */
const SANITIZE_SCHEMA = {
  ...defaultSchema,
  attributes: {
    ...defaultSchema.attributes,
    div: [
      ...(defaultSchema.attributes?.div ?? []),
      ["data-callout", ...Object.keys(CALLOUTS)] as [string, ...string[]],
    ],
  },
};

const buildProcessor = (highlighter: Highlighter, sourceLines: boolean) => {
  const processor = unified()
    .use(remarkParse)
    .use(remarkGfm)
    .use(remarkDirective)
    .use(remarkBlockDirectives)
    .use(remarkRehype)
    .use(rehypeCarryCodeTitle)
    // GitHub's default rules, which already keep `language-*` on a code
    // element — `language-hcl:main.tf` included, which is what lets the fence
    // title survive this step — and which allow `details` and `summary`, which
    // is what lets a collapsible section through with its contents sanitised.
    .use(rehypeSanitize, SANITIZE_SCHEMA)
    // Everything below this line generates trusted markup.
    .use(rehypeHighlight, highlighter)
    .use(rehypeDetails)
    .use(rehypeCallouts)
    .use(rehypeHeadings)
    .use(rehypeExternalLinks);

  if (sourceLines) processor.use(rehypeSourceLines);

  return processor.use(rehypeStringify);
};

/**
 * The pipelines, built once each. Plugins hold no per-document state — the one
 * that would, the heading slugger, creates its own inside the transform — so a
 * single processor is safe to share across concurrent requests.
 *
 * Two of them, keyed by whether the output carries source lines: the flag
 * changes the plugin list, and the only alternative is rebuilding the pipeline
 * (and with it the reference to the highlighter) per request.
 */
const processors = new Map<
  boolean,
  Promise<ReturnType<typeof buildProcessor>>
>();

function getProcessor(sourceLines: boolean) {
  let processor = processors.get(sourceLines);
  if (!processor) {
    processor = getHighlighter().then((h) => buildProcessor(h, sourceLines));
    processors.set(sourceLines, processor);
  }
  return processor;
}

/** Render a guide body to HTML, with the headings it turned out to have. */
export async function renderMarkdown(
  markdown: string,
  {
    /**
     * Mark each block with the source line it came from, for an editor that
     * wants to line the rendering up against the markdown it was typed from.
     */
    sourceLines = false,
  }: { sourceLines?: boolean } = {},
): Promise<RenderedMarkdown> {
  if (markdown.trim().length === 0) return { html: "", toc: [] };

  const processor = await getProcessor(sourceLines);
  // Both passes run before anything parses the text, so `remarkBlockDirectives`
  // — which reads offsets back out of the source it was given — and `data-line`
  // describe the same string. Neither adds or removes a line, so the numbers
  // still point at the markdown the author is looking at.
  const file = await processor.process(
    normaliseListIndents(normaliseDirectiveTitles(markdown)),
  );

  return {
    html: String(file),
    toc: (file.data as { toc?: TocEntry[] }).toc ?? [],
  };
}
